# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-11 07:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationshipOf', models.CharField(max_length=200)),
                ('person1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_person', to='bibleAlpha.Person')),
                ('person2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_object', to='bibleAlpha.Person')),
            ],
        ),
    ]
